# -*- coding: utf-8 -*-
"""DFS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tiQkZ6l4hx6zc39EbBU5EjpxmtYRAxCl
"""

from collections import defaultdict

class Graph:
    def __init__(self):
        self.graph = defaultdict(list)

    def addEdge(self, u, v):
        self.graph[u].append(v)

    def DFSUtil(self, v, visited):
        visited.add(v)
        print(v, end=' ')
        for neighbour in self.graph[v]:
            if neighbour not in visited:
                self.DFSUtil(neighbour, visited)

    def DFS(self, v):
        visited = set()
        self.DFSUtil(v, visited)

if __name__ == "__main__":
    g = Graph()
    g.addEdge('R', 'T')
    g.addEdge('R', 'G')
    g.addEdge('T', 'G')
    g.addEdge('G', 'R')
    g.addEdge('G', 'A')
    g.addEdge('A', 'A')

    print("Berikut adalah Penelusuran Depth First (dimulai dari node C)")
    g.DFS('G')